# Generated by Django 4.1.3 on 2022-12-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
